### ISSUE TITLE
Timeout of 5000ms exceeded calling find on pages 

### ISSUE THREAD

**Issue by laurensiusadi** [DaviTeodoro/notion-clone#1]
Steps to reproduce:
1. Clone project to local
2. Run `npm install`
3. Run `npm run dev`
4. Access `http://localhost:3030/`

Error details:
![firefox_2018-12-08_08-58-19](https://user-images.githubusercontent.com/5661040/49680493-6da89200-fac7-11e8-81ab-d186bf710e67.png)

```
[nodemon] starting `node src/index.js`
  nuxt:build App root: D:\Dev\notion-clone-master\client +0ms
  nuxt:build Generating D:\Dev\notion-clone-master\.nuxt files... +1ms
  nuxt:build Generating files... +43ms
  nuxt:build Generating routes... +34ms
  nuxt:build Building files... +52ms
  nuxt:build Adding webpack middleware... +1s
  ████████████████████ 100%

Build completed in 4.292s



 DONE  Compiled successfully in -6702ms                                                                                                                                                                              8:59:14 AM
info: Feathers application started on localhost:3030
  nuxt:render Rendering url / +0ms
{ Timeout: Timeout of 5000ms exceeded calling find on pages
    at new Timeout (D:\Dev\notion-clone-master\node_modules\@feathersjs\errors\lib\index.js:135:17)
    at Timeout.setTimeout [as _onTimeout] (D:\Dev\notion-clone-master\node_modules\@feathersjs\transport-commons\lib\client.js:66:9)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
  type: 'FeathersError',
  name: 'Timeout',
  message: 'Timeout of 5000ms exceeded calling find on pages',
  code: 408,
  className: 'timeout',
  data: { timeout: 5000, method: 'find', path: 'pages' },
  errors: {},
  statusCode: 500 }
error: Unhandled Rejection at: Promise  Promise {
  <rejected> { Timeout: Timeout of 5000ms exceeded calling find on pages
      at new Timeout (D:\Dev\notion-clone-master\node_modules\@feathersjs\errors\lib\index.js:135:17)
      at Timeout.setTimeout [as _onTimeout] (D:\Dev\notion-clone-master\node_modules\@feathersjs\transport-commons\lib\client.js:66:9)
      at ontimeout (timers.js:436:11)
      at tryOnTimeout (timers.js:300:5)
      at listOnTimeout (timers.js:263:5)
      at Timer.processTimers (timers.js:223:10)
    type: 'FeathersError',
    name: 'Timeout',
    message: 'Timeout of 5000ms exceeded calling find on pages',
    code: 408,
    className: 'timeout',
    data: { timeout: 5000, method: 'find', path: 'pages' },
    errors: {},
    statusCode: 500 } } message=Timeout of 5000ms exceeded calling find on pages, type=FeathersError, name=Timeout, code=408, className=timeout, timeout=5000, method=find, path=pages, , stack=Timeout: Timeout of 5000ms exceeded calling find on pages
    at new Timeout (D:\Dev\notion-clone-master\node_modules\@feathersjs\errors\lib\index.js:135:17)
    at Timeout.setTimeout [as _onTimeout] (D:\Dev\notion-clone-master\node_modules\@feathersjs\transport-commons\lib\client.js:66:9)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10), statusCode=500

```

**Comment by mmalisani** [comment]
I got the same, any fixes?

**Comment by laurensiusadi** [comment]
It seems the index route `/` doesn't return anything, I still don't understand exactly how it works. But just visit `/sign-in` and it should work.
